DROP DATABASE IF EXISTS gtt
CREATE DATABASE GTT
USE gtt;
CREATE TABLE Typ(typ_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, typ VARCHAR(100) NOT NULL);
CREATE TABLE Linia (linia_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, linia_nazwa VARCHAR(5) NOT NULL, wariant_id INT NOT NULL, wariant_nazwa VARCHAR(100) NOT NULL, typ_id INT UNSIGNED NOT NULL, wazny_od DATE, wazny_do DATE, FOREIGN KEY(typ_id) REFERENCES Typ(typ_id) ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE Przystanek( przyst_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, zdik_id VARCHAR(10) NOT NULL UNIQUE,lat DOUBLE ,lng DOUBLE ,przyst_nazwa VARCHAR(100) NOT NULL,ulica VARCHAR(100) NOT NULL,cechy VARCHAR(100));
CREATE TABLE Przypis(przyp_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,przyp_ozn VARCHAR(10) NOT NULL,przyp VARCHAR(300) NOT NULL);
CREATE TABLE Dzien(dzien_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, dzien_nazwa VARCHAR(200) NOT NULL);
CREATE TABLE Rozklad(stop_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, linia_id INT UNSIGNED NOT NULL,przyst_id INT UNSIGNED NOT NULL ,nr_przyst INT UNSIGNED NOT NULL,godzina INT UNSIGNED NOT NULL,minuta INT UNSIGNED NOT NULL,dzien_id INT UNSIGNED NOT NULL,FOREIGN KEY(dzien_id) REFERENCES Dzien(dzien_id) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY(linia_id) REFERENCES Linia(linia_id) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY(przyst_id) REFERENCES Przystanek(przyst_id) ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE Oznaczenie(stop_id INT UNSIGNED NOT NULL,przyp_id INT UNSIGNED NOT NULL,PRIMARY KEY(stop_id, przyp_id), FOREIGN KEY(przyp_id) REFERENCES Przypis(przyp_id) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY(stop_id) REFERENCES Rozklad(stop_id) ON DELETE CASCADE ON UPDATE CASCADE);
